version: "3.9"

name: "server"

services:
  app:
    image: node:latest
    hostname: ${SERVER_HOST}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./:/app
      - ../.env/:/app/.env
    working_dir: /app
    command: "npm run deploy"
    environment:
      - .env
  adminer:
    image: adminer:latest
    ports:
      - ${ADMINER_PORT}:8080
    links:
      - database
    depends_on:
      - database
  database:
    image: postgres:14.8-alpine3.18
    hostname: ${DATABASE_HOST}
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - ../docker/postgres:/var/lib/postgresql/data:./docker/postgres